spring.application.name: commerce
spring.profiles.active: local

spring:
  config:
    import:
      - client.yml
  datasource.hikari.auto-commit: false
  sql.init.mode: always
  data.web.pageable.max-page-size: 100
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties.hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: prod

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:h2:mem:local-db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2.console:
    enabled: true
    path: /h2-console

  sql.init.mode: always

  jpa:
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true

---
spring.config.activate.on-profile: local-test

spring:
  datasource:
    url: jdbc:h2:mem:local-db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true

  sql.init.mode: never